name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to production
      run: |
        lftp -e "set ftp:ssl-allow no; open $FTP_SERVER_TWO; user $FTP_USERNAME $FTP_PASSWORD; mirror -R . /; quit"
