name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
        FTP_SERVER: 217.160.229.108
        FTP_USERNAME: vsantana
        FTP_PASSWORD: A1b2C3d4E5
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install lftp
      run: sudo apt-get install lftp -y
      
    - name: Deploy to production
      run: lftp -u vsantana,A1b2C3d4E5 sftp://217.160.229.108 -e "mirror --ignore-time --parallel=10 --exclude vendor/ --exclude .git/ --exclude .gitignore --exclude .gitlab-ci.yml --reverse --verbose /home/vsantana/ ./; bye"
