name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install lftp
      run: sudo apt-get install lftp -y
      
    - name: Deploy to production
      run: |
        lftp -c "open -u ${{ vars.FTP_USERNAME }},${{ vars.FTP_PASSWORD }} sftp://${{ vars.FTP_SERVER }}; mirror --reverse --verbose --exclude .deploy.yml ./ ./; bye;"
        
