name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    
    env:
      FTP_USERNAME: vsantana
      FTP_PASSWORD: A1b2C3d4E5
      PRODUCTION_SERVER_IP: 217.160.229.108
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install lftp
      run: sudo apt-get install lftp -y
      
    - name: Deploy to production
      run: lftp -c "set ftp:ssl-allow no;open $FTP_SERVER; user $FTP_USERNAME $FTP_PASSWORD; mirror --ignore-time --parallel=10 --reverse --delete --verbose --exclude .deploy.yml ./ ./; bye"
