name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  #deployment:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Rsync Deployer
        uses: imajeetyadav/rsync-deployer@1.0.0
        with:
            HOST: 185.136.91.198
            USERNAME: martatorreprojects.co_fwg0rscgqj
            KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SOURCE_PATH: "."
            TARGET_PATH: "/var/www/vhosts/martatorreprojects.com/test/"
            PORT: 2220
            RSYNC_PARAMETERS: ""
            DELETE_OPTION: "false"
            EXCLUDE_LIST: ".git, .github, "
            DRY_RUN: "false"
