name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    
    env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_FOLDER: ${{ secrets.FTP_FOLDER }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js dependencies
      run: npm install

    - name: Build the application
      run: npm run build

    - name: Install lftp
      run: sudo apt-get install lftp -y

    - name: Deploy to production
      run: lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; set ftp:ssl-force true; set ssl:verify-certificate no; mirror --ignore-time --parallel=10 --exclude vendor/ --exclude .git/ --exclude .github/ --exclude .gitignore --exclude deploy.yml --exclude '.* -> .*' --reverse --verbose ./ $FTP_FOLDER; bye"
