name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    
    env:
      FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      PRODUCTION_SERVER_IP: ${{ secrets.FTP_SERVER }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install lftp
      run: apt-get install lftp -y
      
    - name: Deploy to production
      run: lftp -c "set ftp:ssl-allow no;open $FTP_SERVER; user $FTP_USERNAME $FTP_PASSWORD; mirror --ignore-time --parallel=10 --reverse --delete --verbose --exclude .deploy.yml ./ ./; bye"
